version: '3.7'

services:
  cookie_client:
    container_name: cookie_client
    build:
      context: ./client
      dockerfile: DockerfileClient
    volumes:
      - './client:/client'
    networks:
      - nginx-reverse-proxy-manager_default
      - cookie_network

  cookie_server:
    container_name: cookie_server
    build:
      context: ./server
      dockerfile: DockerfileServer
    ports:
      - "1222:1222"
    volumes:
      - './server:/server'
    networks:
      - nginx-reverse-proxy-manager_default
      - cookie_network
    environment:
      - PORT=1222

  cookie_db:
    container_name: cookie_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'cookiedb'
      MYSQL_USER: 'cdev6490'
      MYSQL_PASSWORD: 'CDev6490??'
      MYSQL_ROOT_PASSWORD: 'CRoot6490??'
    networks:
      - cookie_network
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  adminer_container:
    image: adminer:latest
    environment: 
        ADMINER_DEFAULT_SERVER: cookie_db
        ADMINER_DESIGN: galkaev
    ports: 
      - "1223:8080"
    networks:
      - cookie_network
volumes:
  my-db:
      
networks:
    cookie_network:
        driver: bridge
    nginx-reverse-proxy-manager_default:
        external: true
        driver: bridge